// Frontend skeleton for perfect-web-api-db reference platform.
//
// Boundary rules (from Jankurai JANKURAI_STANDARD.md):
//   - UI owns: forms, generated clients, browser tests.
//   - UI never owns: secrets, durable truth, core authz, direct DB.
//
// All API calls should use the generated client from contracts/openapi.json.
// Do not handwrite fetch() calls that mirror the contract.

import { useState, useEffect } from "react";

// ---------------------------------------------------------------------------
// Types — these should come from a generated client in a real project.
// Generated by: openapi-typescript-codegen (or equivalent)
// Source: contracts/openapi.json
// DO NOT maintain these by hand in production.
// ---------------------------------------------------------------------------

interface Account {
  id: string;
  email: string;
  active: boolean;
  role: "owner" | "admin" | "member" | "viewer";
  organizationId?: string;
}

interface Resource {
  id: string;
  title: string;
  body: string;
  ownerId: string;
}

interface ProblemDetail {
  type: string;
  title: string;
  status: number;
  detail?: string;
}

// ---------------------------------------------------------------------------
// UI States — loading, empty, error, success, permission-denied
// ---------------------------------------------------------------------------

type PageState =
  | { kind: "loading" }
  | { kind: "empty" }
  | { kind: "error"; detail: ProblemDetail }
  | { kind: "denied" }
  | { kind: "success"; accounts: Account[] };

type ResourceState =
  | { kind: "loading" }
  | { kind: "empty" }
  | { kind: "error"; detail: ProblemDetail }
  | { kind: "success"; resources: Resource[] };

// ---------------------------------------------------------------------------
// Components
// ---------------------------------------------------------------------------

function ErrorDisplay({ detail }: { detail: ProblemDetail }) {
  return (
    <div role="alert" className="error-panel" id="error-display">
      <h2>{detail.title}</h2>
      <p>{detail.detail ?? `HTTP ${detail.status}`}</p>
    </div>
  );
}

function PermissionDenied() {
  return (
    <div role="alert" className="denied-panel" id="permission-denied">
      <h2>Access Denied</h2>
      <p>You do not have permission to view this page.</p>
    </div>
  );
}

function EmptyState({ message }: { message: string }) {
  return (
    <div className="empty-state" id="empty-state">
      <p>{message}</p>
    </div>
  );
}

function LoadingSpinner() {
  return (
    <div className="loading" id="loading-spinner" aria-busy="true">
      Loading…
    </div>
  );
}

function AccountList({ accounts }: { accounts: Account[] }) {
  return (
    <table id="account-table" aria-label="Account list">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">Role</th>
          <th scope="col">Active</th>
        </tr>
      </thead>
      <tbody>
        {accounts.map((account) => (
          <tr key={account.id}>
            <td>{account.email}</td>
            <td>{account.role}</td>
            <td>{account.active ? "Yes" : "No"}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function ResourceList({ resources }: { resources: Resource[] }) {
  return (
    <table id="resource-table" aria-label="Resource list">
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Body</th>
        </tr>
      </thead>
      <tbody>
        {resources.map((resource) => (
          <tr key={resource.id}>
            <td>{resource.title}</td>
            <td>{resource.body}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

// ---------------------------------------------------------------------------
// Pages
// ---------------------------------------------------------------------------

function AdminDashboard() {
  const [state, setState] = useState<PageState>({ kind: "loading" });

  useEffect(() => {
    // In production, use the generated API client:
    // import { AdminApi } from "../generated/client";
    // const api = new AdminApi();
    // api.listAccounts().then(...)

    // Simulated for scaffold — no real API call
    setState({ kind: "empty" });
  }, []);

  switch (state.kind) {
    case "loading":
      return <LoadingSpinner />;
    case "empty":
      return <EmptyState message="No accounts found." />;
    case "error":
      return <ErrorDisplay detail={state.detail} />;
    case "denied":
      return <PermissionDenied />;
    case "success":
      return <AccountList accounts={state.accounts} />;
  }
}

function ResourceDashboard() {
  const [state, setState] = useState<ResourceState>({ kind: "loading" });

  useEffect(() => {
    setState({ kind: "empty" });
  }, []);

  switch (state.kind) {
    case "loading":
      return <LoadingSpinner />;
    case "empty":
      return <EmptyState message="No resources found. Create one to get started." />;
    case "error":
      return <ErrorDisplay detail={state.detail} />;
    case "success":
      return <ResourceList resources={state.resources} />;
  }
}

// ---------------------------------------------------------------------------
// App root
// ---------------------------------------------------------------------------

export function App() {
  return (
    <main id="app-root">
      <h1>perfect-web-api-db</h1>
      <nav aria-label="Primary navigation" id="primary-nav">
        <ul>
          <li><a href="#admin">Admin Dashboard</a></li>
          <li><a href="#resources">Resources</a></li>
        </ul>
      </nav>
      <section id="admin-section" aria-labelledby="admin-heading">
        <h2 id="admin-heading">Admin Dashboard</h2>
        <AdminDashboard />
      </section>
      <section id="resources-section" aria-labelledby="resources-heading">
        <h2 id="resources-heading">Resources</h2>
        <ResourceDashboard />
      </section>
    </main>
  );
}
