use jankurai::audit::fs::{inventory_repo_detailed, InventoryOptions};
use jankurai::audit::run_audit;
use std::fs;
use tempfile::tempdir;

#[test]
fn audit_flags_incomplete_generated_zone_metadata_missing_source() {
    let dir = tempdir().unwrap();
    fs::write(dir.path().join("README.md"), "# thin\n").unwrap();
    fs::create_dir_all(dir.path().join("agent")).unwrap();
    fs::write(
        dir.path().join("agent/generated-zones.toml"),
        r#"[[zone]]
path = "out/gen.ts"
source = ""
command = "npm run codegen"
"#,
    )
    .unwrap();

    let report = run_audit(dir.path(), &[]).unwrap();
    let manifest: Vec<_> = report
        .findings
        .iter()
        .filter(|f| {
            f.path == "agent/generated-zones.toml"
                && f.rule_id.as_deref() == Some("HLT-002-GENERATED-MUTATION")
                && f.evidence
                    .iter()
                    .any(|e| e.contains("incomplete reproducibility metadata"))
        })
        .collect();
    assert_eq!(manifest.len(), 1, "{:?}", report.findings);
    assert_eq!(
        manifest[0].rule_id.as_deref(),
        Some("HLT-002-GENERATED-MUTATION")
    );
}

#[test]
fn audit_flags_incomplete_generated_zone_metadata_missing_command() {
    let dir = tempdir().unwrap();
    fs::write(dir.path().join("README.md"), "# thin\n").unwrap();
    fs::create_dir_all(dir.path().join("agent")).unwrap();
    fs::write(
        dir.path().join("agent/generated-zones.toml"),
        r#"[[zone]]
path = "out/gen.ts"
source = "contracts/openapi.yaml"
command = ""
"#,
    )
    .unwrap();

    let report = run_audit(dir.path(), &[]).unwrap();
    assert!(report.findings.iter().any(|f| {
        f.path == "agent/generated-zones.toml"
            && f.evidence
                .iter()
                .any(|e| e.contains("missing or empty `command`"))
    }));
}

#[test]
fn audit_allows_complete_generated_zone_rows() {
    let dir = tempdir().unwrap();
    fs::write(dir.path().join("README.md"), "# thin\n").unwrap();
    fs::create_dir_all(dir.path().join("agent")).unwrap();
    fs::write(
        dir.path().join("agent/generated-zones.toml"),
        r#"[[zone]]
path = "out/gen.ts"
source = "contracts/openapi.yaml"
command = "npm run codegen"
read_only = true
"#,
    )
    .unwrap();
    // Create the declared zone file with a generated header
    fs::create_dir_all(dir.path().join("out")).unwrap();
    fs::write(
        dir.path().join("out/gen.ts"),
        "// Generated by: npm run codegen — DO NOT EDIT\nexport const api = {};\n",
    )
    .unwrap();

    let report = run_audit(dir.path(), &[]).unwrap();
    assert!(!report
        .findings
        .iter()
        .any(|f| f.path == "agent/generated-zones.toml"));
}

#[test]
fn audit_allows_repo_score_json_structured_generated_identity() {
    let dir = tempdir().unwrap();
    fs::write(dir.path().join("README.md"), "# thin\n").unwrap();
    fs::create_dir_all(dir.path().join("agent")).unwrap();
    fs::create_dir_all(dir.path().join(".jankurai")).unwrap();
    fs::write(
        dir.path().join(".jankurai/repo-score.json"),
        r#"{
  "schema_url": "schemas/repo-score.schema.json",
  "generated_at": "0",
  "standard_version": "0.5.0",
  "auditor_version": "0.5.0",
  "schema_version": "1.3.0"
}
"#,
    )
    .unwrap();
    fs::write(
        dir.path().join("agent/generated-zones.toml"),
        r#"[[zone]]
path = ".jankurai/repo-score.json"
source = "crates/jankurai"
command = "cargo run -p jankurai -- . --json .jankurai/repo-score.json --md .jankurai/repo-score.md"
"#,
    )
    .unwrap();

    let report = run_audit(dir.path(), &[]).unwrap();
    assert!(
        !report.findings.iter().any(|f| {
            f.path == ".jankurai/repo-score.json"
                && f.rule_id.as_deref() == Some("HLT-002-GENERATED-MUTATION")
        }),
        "{:?}",
        report.findings
    );
}

#[test]
fn audit_allows_missing_auditor_output_generated_zone() {
    let dir = tempdir().unwrap();
    fs::write(dir.path().join("README.md"), "# thin\n").unwrap();
    fs::create_dir_all(dir.path().join("agent")).unwrap();
    fs::write(
        dir.path().join("agent/generated-zones.toml"),
        r#"[[zone]]
path = ".jankurai/repo-score.json"
source = "crates/jankurai"
command = "cargo run -p jankurai -- . --json .jankurai/repo-score.json --md .jankurai/repo-score.md"
write_policy = "auditor_output"
"#,
    )
    .unwrap();

    let report = run_audit(dir.path(), &[]).unwrap();
    assert!(
        !report.findings.iter().any(|f| {
            f.path == "agent/generated-zones.toml"
                && f.rule_id.as_deref() == Some("HLT-002-GENERATED-MUTATION")
        }),
        "{:?}",
        report.findings
    );
}

#[test]
fn audit_allows_package_lock_json_native_lockfile_identity() {
    let dir = tempdir().unwrap();
    fs::write(dir.path().join("README.md"), "# thin\n").unwrap();
    fs::create_dir_all(dir.path().join("agent")).unwrap();
    fs::write(
        dir.path().join("package-lock.json"),
        r#"{
  "name": "fixture",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {
    "": {
      "name": "fixture"
    }
  }
}
"#,
    )
    .unwrap();
    fs::write(
        dir.path().join("agent/generated-zones.toml"),
        r#"[[zone]]
path = "package-lock.json"
source = "package.json"
command = "npm install"
"#,
    )
    .unwrap();

    let report = run_audit(dir.path(), &[]).unwrap();
    assert!(
        !report.findings.iter().any(|f| {
            f.path == "package-lock.json"
                && f.rule_id.as_deref() == Some("HLT-002-GENERATED-MUTATION")
        }),
        "{:?}",
        report.findings
    );
}

#[test]
fn audit_flags_arbitrary_json_generated_zone_without_identity() {
    let dir = tempdir().unwrap();
    fs::write(dir.path().join("README.md"), "# thin\n").unwrap();
    fs::create_dir_all(dir.path().join("agent")).unwrap();
    fs::create_dir_all(dir.path().join("out")).unwrap();
    fs::write(dir.path().join("out/data.json"), r#"{"value":true}"#).unwrap();
    fs::write(
        dir.path().join("agent/generated-zones.toml"),
        r#"[[zone]]
path = "out/data.json"
source = "contracts/data.schema.json"
command = "cargo run -p jankurai -- generate"
"#,
    )
    .unwrap();

    let report = run_audit(dir.path(), &[]).unwrap();
    assert!(
        report.findings.iter().any(|f| {
            f.path == "out/data.json" && f.rule_id.as_deref() == Some("HLT-002-GENERATED-MUTATION")
        }),
        "{:?}",
        report.findings
    );
}

#[test]
fn audit_protected_generated_zone_entries_still_surface_tracked_rust() {
    let dir = tempdir().unwrap();
    fs::write(dir.path().join("README.md"), "# thin\n").unwrap();
    fs::create_dir_all(dir.path().join("agent")).unwrap();
    fs::create_dir_all(dir.path().join("crates/foo/src")).unwrap();
    fs::create_dir_all(dir.path().join("generated")).unwrap();
    fs::write(
        dir.path().join("crates/foo/src/lib.rs"),
        "pub fn hidden() {\n    let marker = \"legacy\";\n    let _ = marker;\n}\n",
    )
    .unwrap();
    fs::write(
        dir.path().join("generated/out.ts"),
        "// Generated by: test\nexport const ok = true;\n",
    )
    .unwrap();
    fs::write(
        dir.path().join("agent/generated-zones.toml"),
        r#"[[zone]]
path = "crates/foo/src/lib.rs"
source = "contracts/openapi.yaml"
command = "cargo run -p jankurai -- generate"
"#,
    )
    .unwrap();

    let report = run_audit(dir.path(), &[]).unwrap();
    let inventory =
        inventory_repo_detailed(dir.path(), &InventoryOptions::from_policy(dir.path())).unwrap();
    assert!(inventory
        .files
        .iter()
        .any(|file| file.rel_path == "crates/foo/src/lib.rs"));
    assert!(report.findings.iter().any(|finding| {
        finding.path == "agent/generated-zones.toml"
            && finding
                .evidence
                .iter()
                .any(|e| e.contains("targets protected source or control-plane code"))
    }));
}
